'''All organizations tracked with their corresponding repositories'''

repos_core = {'twilio': ['company', 'communication', 'Twilio', 'twilio-python'],
    'confluentinc': ['company', 'communication', 'Confluent', 'ksql'],
    'elastic': ['company', 'other', 'Elastic', 'elasticsearch'],
    'cockroachdb': ['company', 'database', 'CockroachDB', 'cockroach'],
    'mongodb': ['company', 'database', 'MongoDB', 'mongo'],
    'yugabyte': ['company', 'database', 'YugabyteDB', 'yugabyte-db'],
    'ottertune': ['company', 'other', 'Ottertune', 'ot-agent'],
    'launchdarkly': ['company', 'devops', 'LaunchDarkly', 'ld-relay'],
    'gitlabhq': ['company', 'devops', 'GitLab', 'gitlabhq'],
    'jfrog': ['company', 'devops', 'JFrog', 'jfrog-cli'],
    'datadog': ['company', 'data cloud', 'Datadog', 'datadog-agent'],
    'databricks': ['company', 'data cloud', 'Databricks', 'databricks-cli'],
    'snowflakedb': ['company', 'data cloud', 'Snowflake',
        'snowflake-connector-python'],
    'hashicorp': ['company', 'data cloud', 'HashiCorp', 'terraform'],
    'ethereum': ['crypto', 'layer 1', 'Ethereum', 'go-ethereum'],
    'solana-labs': ['crypto', 'layer 1', 'Solana', 'solana'],
    'paritytech': ['crypto', 'layer 0', 'Polkadot', 'substrate'],
    'cosmos': ['crypto', 'layer 0', 'Cosmos', 'cosmos-sdk'],
    'arweaveteam': ['crypto', 'layer 0', 'Arweave', 'arweave'],
    'matter-labs': ['crypto', 'layer 2', 'zkSync', 'zksync'],
    'graphprotocol': ['crypto', 'web3', 'The Graph', 'graph-node'],
    'ethereum-optimism': ['crypto', 'layer 2', 'Optimism', 'optimism'],
    'maticnetwork': ['crypto', 'layer 2', 'Polygon', 'bor'],
    'ava-labs': ['crypto', 'layer 1', 'Avalanche', 'avalanchego'],
    'input-output-hk': ['crypto', 'layer 1', 'Cardano', 'cardano-node'],
    'uniswap': ['crypto', 'web3', 'Uniswap', 'interface'],
    'near': ['crypto', 'layer 1', 'Near', 'nearcore'],
    'smartcontractkit': ['crypto', 'web3', 'Chainlink', 'chainlink'],
    'algorand': ['crypto', 'layer 1', 'Algorand', 'go-algorand'],
    'dfinity': ['crypto', 'layer 1', 'Internet Company', 'ic'],
    'filecoin-project': ['crypto', 'layer 0', 'Filecoin', 'lotus'],
    'bitcoin': ['crypto', 'layer 1', 'Bitcoin', 'bitcoin'],
    'storj': ['crypto', 'web3', 'Storj', 'storj'],
    'brave': ['crypto', 'web3', 'Brave', 'brave-browser'],
    'terra-money': ['crypto', 'layer 1', 'Terra', 'core'],
    'tronprotocol': ['crypto', 'layer 1', 'Tron', 'java-tron'],
    'bnb-chain': ['crypto', 'layer 1', 'Binance', 'bsc'],
    'ripple': ['crypto', 'layer 1', 'Ripple', 'rippled'],
    'consensys': ['crypto', 'layer 1', 'ConsenSys', 'quorum'],
    'aleohq': ['crypto', 'layer 1', 'Aleo', 'snarkos'],
    'offchainlabs': ['crypto', 'layer 2', 'Arbitrum', 'arbitrum']}

